CREATE TABLE Account
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username   VARCHAR(40) UNIQUE NOT NULL,
    password   VARCHAR(60)        NOT NULL,
    balance    REAL               NOT NULL CHECK (balance >= 0),
    status     INT                NOT NULL CHECK (status < 3),
    commission DOUBLE PRECISION   NOT NULL CHECK (0.5 <= commission AND commission <= 5)
);

INSERT INTO Account(username, password, balance, status, commission)
VALUES ('test', '$2a$10$qlLCX6C1Oxe5qf0JCw3t8O2DezB0cE5h.yUnMmmm4siK0Of8Q8pFK', 10000.0, 0, 4.5),
       ('generic', '$2a$10$.Zsf.wsNqmiuUrqOBkm3QOFakL4MzPqziIiEjmjdV2cDrDScVdr1G', 30000.0, 1, 2.5),
       ('common', '$2a$10$74t9Py0t1bAejOL22cuPXOBodF3m9/GNE5eHbOqpeMprK4EghCnCu', 60000.0, 2, 1),
       ('unlimited', '$2a$10$2Dl2MVgQkMJrcrg9uqaUpefYdKHsUdy8hVlRl6HQYjGbTWIjpICFq', 10000000, 2, 0.5);