CREATE TABLE Stock
(
    id             INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_name   VARCHAR(20) UNIQUE NOT NULL,
    purchase_price REAL               NOT NULL CHECK (purchase_price > 0),
    sell_price     REAL               NOT NULL CHECK (0 <= sell_price AND sell_price <= purchase_price),
    quantity       INT                NOT NULL CHECK (0 <= quantity)
);

INSERT INTO Stock(company_name, purchase_price, sell_price, quantity)
VALUES ('Сбербанк', 322.74, 319.35, 150),
       ('Лукойл', 7840, 7750, 20),
       ('Газпром', 155.37, 149.25, 50),
       ('ВК', 629.2, 620, 75),
       ('Яндекс', 104.09, 101.63, 125);